//测试数据
export const CHANGE_NAME = 'CHANGE_NAME';

//home
export const REQUEST_HOT = 'REQUEST_HOT';

export const GET_HOT = 'GET_HOT';

export const REQUEST_SOON = 'REQUEST_SOON';

export const GET_SOON = 'GET_SOON';

//moveList
export const REQUEST_LIST_BY_TYPE = 'REQUEST_LIST_BY_TYPE';

export const GET_LIST_BY_TYPE = 'GET_LIST_BY_TYPE';

export const REQUEST_MORE_BY_TYPE = 'REQUEST_MORE_BY_TYPE';

export const GET_MORE_BY_TYPE = 'GET_MORE_BY_TYPE';

//口碑榜
export const REQUEST_WORD_MOUTH_LIST = 'REQUEST_WORD_MOUTH_LIST';

export const GET_WORD_MOUTH_LIST = 'GET_WORD_MOUTH_LIST';

//北美票房
export const REQUEST_NA_LIST = 'REQUEST_NA_LIST';

export const GET_NA_LIST = 'GET_NA_LIST';

//电影详细信息
export const REQUEST_MOVIE_DETAIL = 'REQUEST_MOVIE_DETAIL';

export const GET_MOVIE_DETAIL = 'GET_MOVIE_DETAIL';

export const GET_MOVIE_PHOTOS = 'GET_MOVIE_PHOTOS';

export const GET_MOVIE_SHORT_COMMENTS = 'GET_MOVIE_SHORT_COMMENTS';

export const GET_MOVIE_LONG_COMMENTS = 'GET_MOVIE_LONG_COMMENTS';

export const REQUEST_MORE_SHORT_COMMENTS = 'REQUEST_MORE_SHORT_COMMENTS';

export const GET_MORE_SHORT_COMMENTS = 'GET_MORE_SHORT_COMMENTS';

export const CLEAR_DETAIL = 'CLEAR_DETAIL';
